lang = "en"
host = "uwe.app"
version = "1.0.0"

[repository]
url = "https://github.com/uwe-app/website/"
edit-path = "edit/main/"

[livereload]
follow-edits = true

#[build]
#layout = "test"

#[script]
#src = "assets/scripts/global.js"

#[sitemap]
#profiles = true

[dependencies]
"std::syntax" = "~1"
"std::listing" = "~1"
"std::core" = { version = "~4.1.11", apply = { styles = ["**"] } }
"std::menu" = { version = "~1", apply = { styles = [ "**" ] } }
"std::sidebar" = { version = "~1", apply = { styles = [ "**" ], scripts = [ "**" ] }}
"std::link" = { version = "~1", features = ["github"] }
"std::note" = { version = "~1.0.1", apply = { styles = [ "**" ] } }
"std::crumbtrail" = { version = "~1", apply = { styles = [ "**" ] } }

[dependencies."font::inter"]
version = "~3"
apply = { styles = [ "**" ] }
features = ["regular"]

[syntax]
inline = true
theme = "Solarized (light)"
#profiles = ["release"]

[transform.html]
toc = true
words = true

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[page]
image = "/assets/img/social.jpg"
description = "Universal Web Editor"
keywords = "Fast, Static, Website, Generator, Markdown, Handlebars, Mdbook, Rust"
authors = [ "tmpfs" ]

[page.http-equiv]
content-security-policy = "default-src data: 'self'; style-src 'self' 'unsafe-inline';"

[page.open-graph]
site_name = "UWE / Universal Web Editor"

[[page.styles]]
src = "assets/styles/print.css"
media = "print"

#[[page.links]]
#as = "audio"
#href = "/my-audio-file.mp3"
#rel = "preload"

[menu]
variants = [{ description = true, suffix = "-idx" }]

[menu.primary]
pages = [
  "/docs/",
]

[menu.primary-footer]
pages = [
  "/faq/",
  "/contact/",
]

[menu.docs]
pages = [
  "/docs/installation/",
  "/docs/getting-started/",
  "/docs/navigation/",
  "/docs/pages/",
  "/docs/content/",
  "/docs/plugins/",
  "/docs/design-patterns/",
  "/docs/search-engines/",
  "/docs/translate/",
  "/docs/publish/",
  "/docs/other/",
  "/docs/reference/",
]

[menu.installation]
pages = [
  "/docs/installation/quick-install/",
  "/docs/installation/release-strategy/",
  "/docs/installation/upgrade/",
  "/docs/installation/project-versioning/",
  "/docs/installation/offline-documentation/",
  "/docs/installation/uninstall/",
]

[menu.getting-started]
pages = [
  "/docs/getting-started/new-project/",
  "/docs/getting-started/build-project/",
  "/docs/getting-started/site-settings/",
  "/docs/getting-started/live-reload/",
  "/docs/getting-started/adding-pages/",
  "/docs/getting-started/front-matter/",
  "/docs/getting-started/links/",
  "/docs/getting-started/content/",
  "/docs/getting-started/styles/",
  "/docs/getting-started/scripts/",
  "/docs/getting-started/layouts/",
  "/docs/getting-started/integrations/",
  "/docs/getting-started/web-manifest/",
  "/docs/getting-started/debugging/",
  "/docs/getting-started/conventions/",
  "/docs/getting-started/directory-listing/",
  "/docs/getting-started/publish/",
  "/docs/getting-started/powered-by/",
]

[menu.navigation]
pages = [
  "/docs/navigation/defining-menus/",
  "/docs/navigation/rendering-menus/",
  "/docs/navigation/next-previous/",
]

[menu.pages]
pages = [
  "/docs/pages/combining-pages/",
  "/docs/pages/removing-pages/",
  "/docs/pages/drafts/",
  "/docs/pages/redirects/",
  "/docs/pages/clean-urls/",
  "/docs/pages/trailing-slash/",
]

[menu.content]
pages = [
  "/docs/content/author-attribution/",
  "/docs/content/reading-time/",
  "/docs/content/feeds/",
  "/docs/content/syntax-highlight/",
  "/docs/content/edit-on-github/",
]

[menu.plugins]
pages = [
  "/docs/plugins/dependencies/",
  "/docs/plugins/apply/",
  "/docs/plugins/using-templates/",
]

[menu.design-patterns]
pages = [
  "/docs/design-patterns/sidebar/",
  "/docs/design-patterns/crumbtrails/",
  "/docs/design-patterns/table-of-contents/",
  "/docs/design-patterns/sticky-header/",
  "/docs/design-patterns/notes/",
]

[menu.seo]
pages = [
  "/docs/search-engines/no-index/",
  "/docs/search-engines/robots/",
  "/docs/search-engines/site-maps/",
]

[menu.translate]
pages = [
  "/docs/translate/introduction/",
  "/docs/translate/languages/",
  "/docs/translate/messages/",
  "/docs/translate/pages/",
]

[menu.publish]
pages = [
  "/docs/publish/self-hosting/",
  "/docs/publish/amazon-web-services/",
]

[menu.other]
pages = [
  "/docs/other/workspaces/",
  "/docs/other/profiles/",
  "/docs/other/hooks/",
  "/docs/other/content-security-policy/",
  "/docs/other/json-templates/",
  "/docs/other/link-catalog/",
  "/docs/other/ignores/",
  "/docs/other/error-page/",
  "/docs/other/strict-mode/",
  "/docs/other/parallel-builds/",
  "/docs/other/ssl-certificates/",
]

[menu.reference]
pages = [
  "/docs/reference/helpers/",
  "/docs/reference/settings/",
  "/docs/reference/commands/",
]

#[profile.inc]
#incremental = true
#pristine = false

[profile.docs]
base = "docs"
base-href = "docs"
layout = "docs"
paths = ["assets", "docs"]

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.stage]
bucket = "stage.uwe.app"

[publish.aws.environments.production]
bucket = "uwe.app"
