lang = "en"
host = "uwe.app"
version = "1.0.0"

[repository]
url = "https://github.com/uwe-app/website/"
edit-path = "edit/main/"

[live-reload]
follow-edits = true

[build]
include-commit = true

#[script]
#src = "assets/scripts/global.js"

#[sitemap]
#profiles = true

[dependencies]
"std::syntax" = "^1.0.1"
"std::listing" = "^1"
"std::alert" = { version = "^1", apply = { styles = [ "**" ] } }
"std::core" = { version = "^5.0.1" }
"std::menu" = { version = "^1", apply = { styles = [ "**" ] } }
"std::sidebar" = { version = "^2.1.0", apply = { styles = [ "**" ] }}
"std::link" = { version = "^1", features = ["github"] }
"std::crumbtrail" = { version = "^1.0.3", apply = { styles = [ "**" ] } }

"uwe::brand::main" = { version = "^1", apply = { styles = [ "**" ] }, path = "../../brand/main" }
"uwe::brand::syntax" = { version = "^1", apply = { styles = [ "**" ] }, path = "../../brand/syntax" }

[syntax.map]
rust = "rs"
#profiles = ["release"]

[transform.html]
toc = true
words = true

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[page]
image = "/assets/img/social.jpg"
description = "Universal Web Editor"
keywords = "Fast, Secure, Static, Website, Generator, Blog, Platform"
authors = [ "tmpfs" ]

#[page.http-equiv]
#content-security-policy = "default-src data: 'self'; style-src 'self' 'unsafe-inline';"

[page.open-graph]
site_name = "UWE / Universal Web Editor"

[[page.styles]]
src = "assets/styles/print.css"
media = "print"

#[[page.links]]
#as = "audio"
#href = "/my-audio-file.mp3"
#rel = "preload"

[menu]
variants = [{ description = true, suffix = "-idx" }]

[menu.primary]
pages = [
  "/faq/",
  "/contact/",
]

[menu.docs]
pages = [
  "/docs/installation/",
  "/docs/tutorials/",
  "/docs/guides/",
  "/docs/cookbook/",
  "/docs/in-depth/",
  "/docs/security/",
  "/docs/reference/",
]

[menu.installation]
pages = [
  "/docs/installation/quick-install/",
  "/docs/installation/release-strategy/",
  "/docs/installation/upgrade/",
  "/docs/installation/project-versioning/",
  "/docs/installation/offline-documentation/",
  "/docs/installation/clean-install/",
  "/docs/installation/uninstall/",
]

[menu.guides]
pages = [
  "/docs/guides/getting-started/",
  "/docs/guides/navigation/",
  "/docs/guides/pages/",
  "/docs/guides/content/",
  "/docs/guides/collections/",
  "/docs/guides/plugins/",
  "/docs/guides/search-engines/",
  "/docs/guides/translate/",
  "/docs/guides/publish/",
]

[menu.tutorials]
pages = [
  "/docs/tutorials/getting-started/",
  "/docs/tutorials/create-workspace/",
  "/docs/tutorials/using-javascript-transpiler/",
  "/docs/tutorials/adding-integration-tests/",
]

[menu.cookbook]
pages = [
  "/docs/cookbook/alerts/",
  "/docs/cookbook/table-of-contents/",
  "/docs/cookbook/directory-listing/",
  "/docs/cookbook/crumbtrails/",
  "/docs/cookbook/sidebar/",
  "/docs/cookbook/sticky-header/",
]

[menu.in-depth]
pages = [
  "/docs/in-depth/build-profiles/",
  "/docs/in-depth/hooks/",
  "/docs/in-depth/build-tools/",
  "/docs/in-depth/test-options/",
  "/docs/in-depth/json-templates/",
  "/docs/in-depth/link-catalog/",
  "/docs/in-depth/ignores/",
  "/docs/in-depth/error-page/",
  "/docs/in-depth/strict-mode/",
  "/docs/in-depth/parallel-builds/",
  "/docs/in-depth/virtual-hosts/",
]

[menu.security]
pages = [
  "/docs/security/content-security-policy/",
  "/docs/security/ssl-certificates/",
]

[menu.getting-started]
pages = [
  "/docs/guides/getting-started/new-project/",
  "/docs/guides/getting-started/build-project/",
  "/docs/guides/getting-started/site-settings/",
  "/docs/guides/getting-started/live-reload/",
  "/docs/guides/getting-started/adding-pages/",
  "/docs/guides/getting-started/front-matter/",
  "/docs/guides/getting-started/links/",
  "/docs/guides/getting-started/content/",
  "/docs/guides/getting-started/styles/",
  "/docs/guides/getting-started/scripts/",
  "/docs/guides/getting-started/layouts/",
  "/docs/guides/getting-started/web-manifest/",
  "/docs/guides/getting-started/debugging/",
  "/docs/guides/getting-started/conventions/",
  "/docs/guides/getting-started/publish/",
  "/docs/guides/getting-started/powered-by/",
]

[menu.navigation]
pages = [
  "/docs/guides/navigation/defining-menus/",
  "/docs/guides/navigation/rendering-menus/",
  "/docs/guides/navigation/next-previous/",
]

[menu.pages]
pages = [
  "/docs/guides/pages/combining-pages/",
  "/docs/guides/pages/removing-pages/",
  "/docs/guides/pages/drafts/",
  "/docs/guides/pages/redirects/",
  "/docs/guides/pages/clean-urls/",
  "/docs/guides/pages/trailing-slash/",
]

[menu.content]
pages = [
  "/docs/guides/content/author-attribution/",
  "/docs/guides/content/reading-time/",
  "/docs/guides/content/feeds/",
  "/docs/guides/content/syntax-highlight/",
  "/docs/guides/content/edit-on-github/",
]

[menu.collections]
pages = [
  "/docs/guides/collections/data-provider/",
  "/docs/guides/collections/map-indices/",
  "/docs/guides/collections/queries/",
  "/docs/guides/collections/page-generators/",
  "/docs/guides/collections/list-pagination/",
]

[menu.plugins]
pages = [
  "/docs/guides/plugins/dependencies/",
  "/docs/guides/plugins/apply/",
  "/docs/guides/plugins/using-templates/",
]

[menu.seo]
pages = [
  "/docs/guides/search-engines/no-index/",
  "/docs/guides/search-engines/robots/",
  "/docs/guides/search-engines/site-maps/",
]

[menu.translate]
pages = [
  "/docs/guides/translate/introduction/",
  "/docs/guides/translate/languages/",
  "/docs/guides/translate/messages/",
  "/docs/guides/translate/pages/",
]

[menu.publish]
pages = [
  "/docs/guides/publish/self-hosting/",
  "/docs/guides/publish/amazon-web-services/",
]

[menu.reference]
pages = [
  "/docs/reference/helpers/",
  "/docs/reference/settings/",
  "/docs/reference/commands/",
  "/docs/reference/server/",
  "/docs/reference/environment-variables/",
  "/docs/reference/troubleshooting/",
]

#[profile.inc]
#incremental = true
#pristine = false

[profile.docs]
base = "docs"
base-href = "docs"
layout = "docs"
paths = ["assets", "docs"]

[publish.aws]
region = "ap-southeast-1"
credentials = "uwe"

[publish.aws.environments.stage]
bucket = "stage.uwe.app"

[publish.aws.environments.production]
bucket = "uwe.app"
