lang = "en"
host = "uwe.app"
version = "1.0.0"

[repository]
url = "https://github.com/uwe-app/website/"
edit-path = "edit/site/"

#[script]
#src = "assets/scripts/global.js"

#[sitemap]
#profiles = true

[dependencies]
#"std::core" = { git = "https://github.com/uwe-app/plugins", version = "~1" }
#"std::core" = { version = "~1" }
"std::core" = { path = "../../plugins/std/core", version = "~2" }
"std::link" = { path = "../../plugins/std/link", version = "~1", features = ["github"] }
"std::listing" = { path = "../../plugins/std/listing", version = "~1" }
"std::note" = { version = "~1", apply = { styles = [ "**" ] } }
"std::crumbtrail" = { path = "../../plugins/std/crumbtrail", version = "~1", apply = { styles = [ "**" ] } }
"css::new" = { version = "~1", apply = { styles = [ "**" ] } }

[dependencies."font::inter"]
path = "../../plugins/font/inter"
version = "~3"
apply = { styles = [ "**" ] }
features = ["regular"]

#[dependencies."font::awesome"]
#path = "../../plugins/font/awesome"
#version = "~5"
#apply = { styles = [ "/docs/plugins/**" ] }

#[dependencies."font::source-code-pro"]
#path = "../../plugins/font/source-code-pro"
#version = "~1"
#apply = { styles = [ "/docs/plugins/**" ] }

#[dependencies."std::book"]
#path = "../../plugins/std/book"
#version = "~1"
#apply = { styles = [ "/docs/plugins/**" ], scripts = [ "/docs/plugins/**" ], layouts = { main = [ "/docs/plugins/**" ] } }

#[dependencies."lib::highlight"]
#path = "../../plugins/lib/highlight"
#version = "~10"
#apply = { scripts = [ "/docs/**/**" ], styles = [ "/docs/**/**" ] }

[syntax]
inline = true
theme = "Solarized (light)"
#profiles = ["release"]

#[styles]
#main = ["/assets/styles/main.css"]

#[scripts]
#main = ["/assets/highlight.pack.js"]

[transform.html]
toc = true

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[page]
image = "/assets/img/social.jpg"
description = "Universal Web Editor"
keywords = "Fast, Static, Website, Generator, Markdown, Handlebars, Mdbook, Rust"
authors = [ "tmpfs" ]

[page.open-graph]
site_name = "UWE / Universal Web Editor"

#[[page.links]]
#as = "audio"
#href = "/my-audio-file.mp3"
#rel = "preload"

[menu]
#sidebar = { file = "MENU.md" }
main = { pages = ["/docs/", "/faq/"], description = true }
docs = { directory = "/docs/" }

[menu.getting-started-idx]
description = true
pages = [
  "/docs/getting-started/new-project/",
  "/docs/getting-started/build-project/",
  "/docs/getting-started/site-settings/",
  "/docs/getting-started/adding-pages/",
  "/docs/getting-started/front-matter/",
  "/docs/getting-started/links/",
  "/docs/getting-started/customize/",
  "/docs/getting-started/layouts/",
  "/docs/getting-started/debugging/",
  "/docs/getting-started/conventions/",
  "/docs/getting-started/directory-index/",
]

[menu.pages-idx]
description = true
pages = [
  "/docs/pages/remove/",
  "/docs/pages/drafts/",
  "/docs/pages/redirects/",
  "/docs/pages/clean-urls/",
  "/docs/pages/trailing-slash/",
]

[menu.content-idx]
description = true
pages = [
  "/docs/content/author-attribution/",
  "/docs/content/feeds/",
  "/docs/content/syntax-highlight/",
  "/docs/content/edit-on-github/",
]

[menu.seo-idx]
description = true
pages = [
  "/docs/search-engines/no-index/",
  "/docs/search-engines/robots/",
  "/docs/search-engines/site-maps/",
]

[menu.other-idx]
description = true
pages = [
  "/docs/other/hooks/",
  "/docs/other/link-catalog/",
  "/docs/other/ignores/",
  "/docs/other/commands/",
  "/docs/other/error-page/",
  "/docs/other/strict-mode/",
  "/docs/other/parallel-builds/",
  "/docs/other/ssl-certificates/",
]

[menu.design-patterns-idx]
description = true
pages = [
  "/docs/design-patterns/crumbtrails/",
  "/docs/design-patterns/table-of-contents/",
  "/docs/design-patterns/notes/",
]

[menu.translate-idx]
description = true
pages = [
  "/docs/translate/introduction/",
  "/docs/translate/languages/",
  "/docs/translate/messages/",
]

#[profile.inc]
#incremental = true
#pristine = false

[profile.dist]
include-index = true

[profile.docs]
base = "docs"
base-href = "docs"
layout = "partials/docs-layout.hbs"
paths = ["assets", "docs"]

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"
environments = {stage = {prefix = "stage"}, production = {prefix = "production"}}
